[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  PIP_VERSION = "23.3.1"
  PYTHON_VERSION = "3.8"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
